### ISSUE TITLE
Error when mix hex.publish

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/pelemay#155]
**Describe the bug**
An error occurs when `mix hex.publish`

**To Reproduce**
1. On Pelemay directory
2. Run in the command `mix hex.publish`
3. See error:

```
Building docs...
** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{:run, 1}, [{:type, 86, :fun, [{:type, 86, :product, [{:ann_type, 86, [{:var, 86, :command_line_args}, {:type, 0, :list, [{:type, 86, :binary, []}]}]}]}, {:type, 86, :any, []}]}]}
    (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:385: anonymous fn/2 in ExDoc.Retriever.get_impls/1
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:384: ExDoc.Retriever.get_impls/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:164: ExDoc.Retriever.get_module_data/2
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:115: ExDoc.Retriever.generate_node/3
    (elixir 1.11.2) lib/enum.ex:3421: Enum.flat_map_list/2
    (elixir 1.11.2) lib/enum.ex:3422: Enum.flat_map_list/2
```

**Expected behavior**
No error occurs and it can be published successfully.

**Screenshots**
None.

**Desktop (please complete the following information):**

```elixir
iex(1)> CpuInfo.all_profile
%{
  compiler: %{
    apple_clang: [
      %{
        bin: "/usr/bin/clang",
        type: :apple_clang,
        version: "12.0.0",
        versions: "Apple clang version 12.0.0 (clang-1200.0.32.27)"
      }
    ],
    "apple_clang++": [
      %{
        bin: "/usr/bin/clang++",
        type: :"apple_clang++",
        version: "12.0.0",
        versions: "Apple clang version 12.0.0 (clang-1200.0.32.27)"
      }
    ],
    cc_env: [],
    cflags_env: "-I/usr/local/opt/llvm/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/mysql@5.6/include -I/usr/local/opt/openblas/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/lapack/include",
    clang: [
      %{
        bin: "/usr/local/opt/llvm/bin/clang",
        type: :clang,
        version: "11.0.0",
        versions: "clang version 11.0.0"
      }
    ],
    "clang++": [
      %{
        bin: "/usr/local/opt/llvm/bin/clang++",
        type: :"clang++",
        version: "11.0.0",
        versions: "clang version 11.0.0"
      }
    ],
    cxx_env: [],
    cxxflags_env: "",
    "g++": [
      %{
        bin: "/usr/bin/g++",
        type: :"apple_clang++",
        version: "12.0.0",
        versions: "Apple clang version 12.0.0 (clang-1200.0.32.27)"
      },
      %{
        bin: "/usr/local/bin/g++-7",
        type: :"g++",
        version: "7.5.0",
        versions: "g++-7 (Homebrew GCC 7.5.0_2) 7.5.0"
      },
      %{
        bin: "/usr/local/bin/g++-8",
        type: :"g++",
        version: "8.4.0",
        versions: "g++-8 (Homebrew GCC 8.4.0_1) 8.4.0"
      }
    ],
    gcc: [
      %{
        bin: "/usr/bin/gcc",
        type: :apple_clang,
        version: "12.0.0",
        versions: "Apple clang version 12.0.0 (clang-1200.0.32.27)"
      },
      %{
        bin: "/usr/local/bin/gcc-7",
        type: :gcc,
        version: "7.5.0",
        versions: "gcc-7 (Homebrew GCC 7.5.0_2) 7.5.0"
      },
      %{
        bin: "/usr/local/bin/gcc-8",
        type: :gcc,
        version: "8.4.0",
        versions: "gcc-8 (Homebrew GCC 8.4.0_1) 8.4.0"
      }
    ],
    ldflags_env: "-L/usr/local/opt/llvm/lib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/mysql@5.6/lib -L/usr/local/opt/openblas/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/lapack/lib"
  },
  cpu: %{
    cpu_model: "18-Core Intel Xeon W",
    cpu_models: ["18-Core Intel Xeon W"],
    cpu_type: "x86_64",
    hyper_threading: :enabled,
    num_of_cores_of_a_processor: 18,
    num_of_processors: 1,
    num_of_threads_of_a_processor: 36,
    os_type: :macos,
    total_num_of_cores: 18,
    total_num_of_threads: 36
  },
  cuda: %{cuda: false},
  elixir: %{version: "1.11.2"},
  erlang: %{otp_version: 23},
  kernel: %{
    kernel_release: "20.1.0",
    kernel_version: "Darwin 20.1.0",
    system_version: "macOS 11.0.1 (20B50)"
  },
  metal: %{metal: false}
}
```

**Additional context**
None.

**Comment by zacky1972** [comment]
@supersimple said "Eric says you probably need to update ex_doc", so I did `mix deps.update --all`.

Then, `mix docs` got another error: 

```
Generating docs...
** (ArgumentError) argument error
    (stdlib 3.13.2) :ets.insert(ExDoc.Refs, [{{:function, Analyzer, :listing_literal, 2}, :public}, {{:function, Analyzer, :parse, 1}, :public}, {{:function, Analyzer, :polynomial_map, 1}, :public}, {{:function, Analyzer, :supported?, 1}, :public}, {{:module, Analyzer}, :public}])
    lib/ex_doc/refs.ex:72: ExDoc.Refs.insert/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:88: ExDoc.Retriever.docs_chunk/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:60: ExDoc.Retriever.get_module/2
    (elixir 1.11.2) lib/enum.ex:3421: Enum.flat_map_list/2
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2
    (ex_doc 0.21.2) lib/ex_doc.ex:26: ExDoc.generate_docs/3
    (ex_doc 0.21.2) lib/mix/tasks/docs.ex:349: anonymous fn/6 in Mix.Tasks.Docs.run/3
```

**Comment by zacky1972** [comment]
Strange... The versions of `ex_doc` are different... (The error of `mix docs` said 0.21.2, though `mix deps.update --all` said 0.23.0.

```
mix deps.update --all                       
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cpu_info 0.2.2
  earmark_parser 1.4.12
  ex_doc 0.23.0
  file_system 0.2.10
  makeup 1.0.5
  makeup_elixir 0.15.0
  mix_test_watch 1.0.2
  nimble_parsec 1.1.0
  ring_logger 0.8.1
```

**Comment by zacky1972** [comment]
I can do it by the following:

```
> cd ..
> rm -rf pelemay
> git clone git@github.com:zeam-vm/pelemay.git
> cd pelemay
> mix docs
```
